### ISSUE TITLE
your youtube api key is in the code

### ISSUE THREAD

**Issue by aenriii** [Brian-Gaffney/YouTube-video-length-Chrome-extension#3]
i know this is like 4 years late but anyone can see your youtube api key

**Comment by aenriii** [comment]
you might want to fix that (look into `.gitignore` files)

**Comment by Brian-Gaffney** [comment]
Hi jdadonut.

Thanks for reviewing the code.

The API key is not secret.
It gets built into the extension and published to the extension store.
It can also be viewed in every network request the extension makes.

There is no sensible way to hide the API key for a Chrome extension.
